"""empty message

Revision ID: 4ec7a650ffd8
Revises: 510e436cf28e
Create Date: 2019-03-26 14:03:29.457838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec7a650ffd8'
down_revision = '510e436cf28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagegroup_timestamp'), 'imagegroup', ['timestamp'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_filename', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('img_data', sa.String(length=264), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('imagegroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imagegroup_id'], ['imagegroup.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_index(op.f('ix_imagegroup_timestamp'), table_name='imagegroup')
    op.drop_table('imagegroup')
    # ### end Alembic commands ###
